### PR TITLE
Fix check smarty name

### PR DESCRIPTION
**Pull request by matthieumota**
There is a little typo on smarty name for check part.

### CODE REVIEW

**Review by Scritik — APPROVED** [review]

**Comment by dvitcompte** [comment]
Hello, 
the problem is that in PS1.6 the mail var is 'cheque_name' but in PS1.7 the mail var was changed to 'check_name'.
So depending on the PS version you want to generate your template the cheque mail will be wrong.
I used a existing ps1.7 specific var to check the PS version but maybe there is a better solution ?
Regards,

**Comment by Scritik** [comment]
Hi,

Yes you are right.
I think that the best solution is to revert this commit and for the 1.7 versions, we should add the two variables in:

https://github.com/PrestaShop/ps_emailsmanager/blob/master/ps_emailsmanager.php#L90

This way, we keep the old names for the 1.6 versions.

**Comment by dvitcompte** [comment]
Yes, here my working update for PrestaShop 1.7 ps_emailsmanager module cheque>check typo : 
```
public function hookActionGetExtraMailTemplateVars($params)
{
    if (version_compare(_PS_VERSION_, '1.7', '>=') && $params['template'] == 'cheque') {
        $params['extra_template_vars']['{cheque_name}'] = $params['template_vars']['{check_name}'];
        $params['extra_template_vars']['{cheque_address_html}'] = $params['template_vars']['{check_address_html}'];
    }
    $params['extra_template_vars']['{passwd}'] = '*********';
}
```

**Comment by Scritik** [comment]
Looks good to me, can you make a PR so I can make a test on my side? Thanks.

**Pull request merged**
